dataset: "Chem"

path:
  corpus_path: "/data/conggaoxiang/Chem"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "/data/conggaoxiang/Chem"
  preprocessed_path: "/data/conggaoxiang/V2C/V2C_Code/example_Chem16_framelevel/chem"  # chem
  # Cheme
  # "/data/conggaoxiang/V2C/V2C_Code/example_G_16/MovieAnimation"
  # "/data/conggaoxiang/V2C/V2C_Code/example_GRID_wav16_frames/MovieAnimation"
  # "/data/conggaoxiang/V2C/V2C_Code/example_G_16/MovieAnimation"
  # "/data/conggaoxiang/V2C/V2C_Code/example_V2C16_HiFiGAN_E1/MovieAnimation"
  # RIGHT
  # "/data/conggaoxiang/V2C/V2C_Code/example_V2C16_Frame_l/MovieAnimation"
  # "/data/conggaoxiang/V2C/V2C_Code/example_V2C16_rm_silence/MovieAnimation"
  # "/data/conggaoxiang/V2C/V2C_Code/example_D_2/example_DD/example_D/MovieAnimation"

  # "/data/conggaoxiang/V2C/V2C_Code/public_processed_data_codebook8/MovieAnimation"
  # "./preprocessed_data/MovieAnimation"
  # "/data/conggaoxiang/V2C/V2C_Code/GT_A/MovieAnimation"

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 16000  # To make a fair comparison with other methods, we support the sampling rate of 16KHz for the Chem dataset.
    max_wav_value: 32768.0
  stft:
    filter_length: 1024  #
    hop_length: 160 # For adapt the sampling rate of 16KHz
    win_length: 640 # For adapt the sampling rate of 16KHz
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000  #  please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "frame_level" # Fixed this setting, and our method can not support 'phoneme_level'.
    normalization: True
  energy:
    feature: "frame_level" # Fixed this setting, and our method can not support 'phoneme_level'.
    normalization: True
  emotion:
    n_emotion: 8

Padding:
  preprocess: True  # False, padding for mel, pitch, energy, and duration

last_n_speaker: 0 # number of speakers on the last dataset
with_gt: False # when generating speech by synthesize.py, whether synthesize gt as well
